### ISSUE TITLE
fix: Warning: Operand of null-aware operation '?.' has type 'ImageCache' which excludes null.

### ISSUE THREAD

**Issue by Bassiuz** [Betterment/alchemist#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

0.3.3

### Description

Whenever running test I get a warning in the console

```
../.pub-cache/hosted/pub.dartlang.org/alchemist-0.3.3/lib/src/alchemist_test_variant.dart:39:5: Warning: Operand of null-aware operation '?.' has type 'ImageCache' which excludes null.
 - 'ImageCache' is from 'package:flutter/src/painting/image_cache.dart' ('../fvm/versions/3.0.1/packages/flutter/lib/src/painting/image_cache.dart').
    imageCache?.clear();
    ^
```
    
Tests still work correctly but warnings fill terminal.

### Steps to reproduce

Use Alchemist 0.3.3 with Flutter > 3 and run tests.

flutter_test_config.dart for reference:

```
Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  await loadAppFonts();

  return AlchemistConfig.runWithConfig(
    config: AlchemistConfig(
      platformGoldensConfig: PlatformGoldensConfig(platforms: <HostPlatform>{
        HostPlatform.macOS,
        HostPlatform.windows,
      }),
    ),
    run: testMain,
  );
}
```

### Expected behavior

When running it shouldn't warn about ImageCache issues.

**Comment by jeroen-meijer** [comment]
Hi there, thanks for opening an issue!

This issue appears to have been fixed in #51 when the package was upgraded to Flutter 3.
[That line has since been edited](https://github.com/Betterment/alchemist/blame/e379bdd6e84e7f91bc5ac4e3ab60d3a86bf5bbcb/lib/src/alchemist_test_variant.dart#L39), so this warning should not pop up once a new version has been released on pub.

Hope this helps. Closing this :)
