### ISSUE TITLE
request: ensure that error messages are always legible

### ISSUE THREAD

**Issue by alestiago** [Betterment/alchemist#63]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

I would like to be able to read the error message from the golden file.

### Description

As a developer, I would like to be able to read the error message from a golden file. 

### Reasoning

Allowing to view the error message from the golden file facilitates debugging and, hence makes the DX much nicer.

For example, the following image should have the error shown in a legible font (not Ahem):
<img width="215" alt="Screenshot 2022-06-06 at 11 20 12" src="https://user-images.githubusercontent.com/44524995/172143107-48e8fdaf-4b28-49fc-895f-24454b7b2385.png">

**Comment by jeroen-meijer** [comment]
Thanks for reporting this!

Looks like our blocked font renderer works a little _too_ well. We'll have a look!

**Comment by jeroen-meijer** [comment]
@Kirpal Do you happen to know if it's easy for us to disable the blocked text renderer AND our font mechanics when an error occurs?

**Comment by Kirpal** [comment]
We could probably update the painting context to change how we render the [error render object](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/error.dart). However, I'm wondering how useful that is because you could also use the platform golden to see the message. If someone were to commit a golden with rendering issues, then the ci golden test would fail with font inconsistencies which seems undesirable.
